### ISSUE TITLE
Shallow (protocol) mappers

### ISSUE THREAD

**Issue by sobolevn** [dry-python/mappers#121]
Sometimes when I want to create a domain model - I don't actually need a real class.

Example:

```python
def send_email(email: MyEmailDTO) -> None:
      return django_send_email(to=[email.to], subject=email.subject, body=email.body)
```

As shown in this example models can (and frequently) used as just data. In this case creating a DTO is possible, but not wanted. Because it just creates useless object and slow things down. 

Protocols on the other hand is the solution we need:
- It typechecks things
- It does not have any runtime overhead

So, this is how API might look like:

```python
EmailProtocol = mappers.shallow_map(MyEmailModel)

def send_email(email: EmailProtocol) -> None:
     ...
```

Where `shallow_map` is something like this:

```python
def shallow_map(django_model: models.Model) -> type:
      return type(django_model.__class__.__qualname__ + 'Protocol', (Protocol, ), {'field1': int, **other_fields}
```

**Comment by proofit404** [comment]
Hi, thank you for the report.

The main point of the domain model (entity) class is the ability to encapsulate **behavior** of something real.

Let's consider a simple use case (usage scenario in the project).

If we have domain models, our steps will look like this:
```python
class Purchase:
    def check_balance(self, ctx):
        if ctx.user.can_afford(ctx.product):
```
And if we use plain data, it'll look like this:
```python
class Purchase:
    def check_balance(self, ctx):
        if ctx.user.balance >= ctx.product.price:
```
Otherwise, the whole `mappers` library could be replaced by [values list returning named tuples](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#values-list).
```pycon
>>> Entry.objects.values_list('id', 'headline', named=True)
<QuerySet [Row(id=1, headline='First entry'), ...]>
```
Also, `mappers` library will never treat data source (the Django model) as a source of truth. We'll only check that data source conforms to the contract defined by Entity class.

If you want to type check existed protocol against the values list result, it's better to address this issue in the typed Django organization.

If you want to generate protocols from the Django model, I suggest creating another library.

Both cases are out of the goal of the `mappers` library.

I hope I explain the reasoning well enough.

Have a good day :tada: 

Best regards, 
Artem.
