### ISSUE TITLE
Deprecate typing.

### ISSUE THREAD

**Issue by proofit404** [dry-python/mappers#197]
Internal typing implementation is way too flaky to build our API around it. Future python version will be even more complicated to do it properly. See #194 and https://github.com/asottile/flake8-typing-imports

We would replace typing interface with a set of decorators:
```python
@mapper.reader.single
def load_user(user_id):
    return UserTable.objects.filter(pk=user_id)

@mapper.reader.optional
def load_user(user_id):
    return UserTable.objects.filter(pk=user_id)

@mapper.reader.sequence
def load_users():
    return UserTable.objects.all()
```
Type hints are optional and will not be used at all for our implementation. Python 2 will be able to drop the `typing` module of hard dependency.

Entity classes are not needed for reader declaration since mapper already has its class.

**Comment by sobolevn** [comment]
That's a good idea! Because `List[User]` was incorrect for `UserTable.objects.all()`, because the real type is `QuerySet[User]` (thanks to django-stubs).

I would say that the next step is to add typing support for these decorators. I would suggest adding `Protocol`-based types. Like `Iterable[T]` or so on, so we would be free to chose the real implementation.
